# Generated by Django 4.2.5 on 2023-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Введите заголовок поста', verbose_name='Заголовок')),
                ('img', models.ImageField(help_text='Загрузите изображение для записи', upload_to='history/', verbose_name='Изображение')),
                ('status', models.BooleanField(default=True, help_text='Отображает запись на странице', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
