# Generated by Django 4.2.5 on 2023-09-09 08:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите полностью ФИО человека', max_length=255, verbose_name='Имя человека')),
                ('text', models.TextField(blank=True, help_text='Введите текст, который будет отображаться на странице с записью', verbose_name='Текст контента')),
                ('poster', models.ImageField(help_text='Загрузите изображение для записи', upload_to='people/', verbose_name='Главное изображение')),
                ('status', models.BooleanField(default=True, help_text='Отображает запись на странице', verbose_name='Статус')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='PeopleImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='people/people_list/', verbose_name='Дополнительные изображения')),
                ('status', models.BooleanField(default=True, help_text='Отображает изображение на странице', verbose_name='Статус')),
                ('people', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
