# Generated by Django 4.2.5 on 2023-09-11 14:33

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название для заголовка проблемы', max_length=256, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Введите контент для описания проблемы', null=True, verbose_name='Контент')),
                ('poster', models.ImageField(help_text='Загрузите изображение для записи', upload_to='problem/', verbose_name='Главное изображение')),
                ('status', models.BooleanField(default=True, help_text='Отображает запись на странице', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='ProblemImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='problem/problem_item/', verbose_name='Дополнительные изображения')),
                ('status', models.BooleanField(default=True, help_text='Отображает изображение на странице', verbose_name='Статус')),
                ('people', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
